### ISSUE TITLE
Feedback zur ersten Pflichtübung

### ISSUE THREAD

**Issue by 1233334** [tpe-lecture/repo-40#1]
**Paketname**
Der Paketname ist in Ordnung.
[-0 Punkte]

**JavaDoc**
Kein JavaDoc vorhanden. 
[-10 Punkte]

**Coding-Standard**
JUNIT Tests können in einer Klasse erfasst werden. (Bsp: jeder Testfall für die jeweilige Klasse in einer Testmethode schreiben)
[-1 Punkte]

**Figuren**
•	Bei der Klasse Gerade sollte eine Fläche von 0 herauskommen, lt. Code ist die Länge = Fläche
•	Alle Get-Methoden außer getFlaeche() sind nicht notwendig
•	Abgesehen von den Klassen Figur und Gerade sind in den anderen Klassen keine Attribute notwendig
 [-4 Punkte]

**UML**
•	Konstruktoren müssen unterstrichen werden
[-1 Punkte]

**Bewertung**
**84 Punkte**

**Bitte korrigieren Sie die genannten Fehler bis zur nächsten Übungsstunde, checken Sie die Verbesserung ein und schließen Sie dann dieses Issue.**

**Comment by lucas2412** [comment]
Ist es denn nicht ok ein Paket "de.hs-ma.tpe.gruppe40.Lucas.Aylin" zu erstellen und in diesem Paket wiederum ein Paket "Figuren" mit den Klassen zu machen?

**Comment by 1233334** [comment]
Hi Lucas,

Ja ihr ward diejenigen bei denen ich mir Gedanken gemachte habe. Der 
Paketname komplett ist absolut richtig, ihr habt da nur in dem Package 
nochmal eins gemacht mit Figuren. Ich wollte dies mit Herr Smits 
absprechen und dann die Punktzahl (höchstwahrscheinlich) ändern.

Ich hab es erstmal schlechter bewertet, damit ihr Puffer für eine 
Verbesserung habt :-)

Mfg Hasan


Am Wed, 14 Oct 2015 15:04:47 -0700
  schrieb lucas2412 <notifications@github.com>:
