### ISSUE TITLE
Testat - 3: Feedback

### ISSUE THREAD

**Issue by Tubiii** [tpe-lecture/repo-40#2]
- In der Klasse GameController, Methode squadAuswahl: Das Abbruchkriterium für die while-Schleife existiert ausschließlich für diesen einen Zweck und wird dann false gesetzt, wenn squad.getKontostand() < 70; direkt die Bedingung in die while-Schleife übernehmen	-2
- Live-Testat: es gab einige Verwirrungen, kleine Schwierigkeiten bei der Einführung von Mojo, konnte aber dann noch umgesetzt werden	-10
- <b>Gesamtpunktzahl	88</b>

**Comment by lucas2412** [comment]
Bei mir sind die Punkte in Moodle bei Pflichübung 3 eingetragen. Sollten diese nicht bei Pflichtübung 2 stehen?

**Comment by Tubiii** [comment]
Nun nicht mehr! ;)
